/**
 * Phase 0 & Phase 5 Security Verification Suite for firestore.rules
 * Verifies that all "Dirty Dozen" adversarial payloads are rejected with PERMISSION_DENIED.
 */

export interface SecurityTestCase {
  id: number;
  name: string;
  collection: string;
  docId: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  auth: { uid: string; email_verified: boolean } | null;
  payload?: Record<string, unknown>;
  expectedResult: 'PERMISSION_DENIED';
}

export const DIRTY_DOZEN_SECURITY_TESTS: SecurityTestCase[] = [
  {
    id: 1,
    name: 'Unverified Email Spoof on User Profile Creation',
    collection: 'users',
    docId: 'user_1',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: false },
    payload: {
      uid: 'user_1',
      displayName: 'Spoofed User',
      preferredCity: 'New York, NY',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 2,
    name: 'Cross-User Profile Read Attempt',
    collection: 'users',
    docId: 'user_2',
    operation: 'get',
    auth: { uid: 'user_1', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 3,
    name: 'Shadow Field Injection on Booking Create',
    collection: 'bookings',
    docId: 'booking_1',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      userId: 'user_1',
      clientName: 'Clara Vance',
      photographerId: 'photog_1',
      photographerName: 'Julian Vance',
      category: 'Wedding',
      shootDate: '2026-10-15',
      shootTime: '09:00 AM',
      location: 'Manhattan, NY',
      hours: 4,
      packageName: 'Editorial Signature',
      totalPrice: 1200,
      notes: 'Natural light preferred',
      status: 'confirmed',
      isAdminOverride: true, // Ghost field rejected by hasOnly()
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 4,
    name: 'Orphaned Booking Write Without Existing User Profile',
    collection: 'bookings',
    docId: 'booking_2',
    operation: 'create',
    auth: { uid: 'non_existent_user', email_verified: true },
    payload: {
      userId: 'non_existent_user',
      clientName: 'Ghost User',
      photographerId: 'photog_1',
      photographerName: 'Julian Vance',
      category: 'Portrait',
      shootDate: '2026-10-18',
      shootTime: '10:00 AM',
      location: 'SoHo Studio, NY',
      hours: 2,
      packageName: 'Essential Session',
      totalPrice: 480,
      notes: '',
      status: 'confirmed',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 5,
    name: 'Identity Spoofing on Booking Create (Mismatched userId)',
    collection: 'bookings',
    docId: 'booking_3',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      userId: 'user_2',
      clientName: 'Clara Vance',
      photographerId: 'photog_1',
      photographerName: 'Julian Vance',
      category: 'Fashion',
      shootDate: '2026-10-20',
      shootTime: '02:00 PM',
      location: 'Brooklyn Navy Yard',
      hours: 3,
      packageName: 'Editorial Signature',
      totalPrice: 950,
      notes: '',
      status: 'confirmed',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 6,
    name: 'Denial of Wallet Oversized Notes String (> 500 chars)',
    collection: 'bookings',
    docId: 'booking_4',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      userId: 'user_1',
      clientName: 'Clara Vance',
      photographerId: 'photog_1',
      photographerName: 'Julian Vance',
      category: 'Events',
      shootDate: '2026-10-22',
      shootTime: '06:00 PM',
      location: 'Tribeca Rooftop',
      hours: 4,
      packageName: 'Full Coverage',
      totalPrice: 1400,
      notes: 'X'.repeat(1024),
      status: 'confirmed',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 7,
    name: 'Invalid Date Format Poisoning',
    collection: 'bookings',
    docId: 'booking_5',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      userId: 'user_1',
      clientName: 'Clara Vance',
      photographerId: 'photog_1',
      photographerName: 'Julian Vance',
      category: 'Birthday',
      shootDate: '15-10-2026', // Violates ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
      shootTime: '01:00 PM',
      location: 'Chelsea Loft',
      hours: 2,
      packageName: 'Essential Session',
      totalPrice: 500,
      notes: '',
      status: 'confirmed',
      createdAt: 'SERVER_TIMESTAMP',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 8,
    name: 'Terminal State Bypass (Updating an Already Cancelled Booking)',
    collection: 'bookings',
    docId: 'booking_cancelled_1',
    operation: 'update',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      status: 'confirmed',
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 9,
    name: 'Unauthorized TotalPrice Tampering During Reschedule Update',
    collection: 'bookings',
    docId: 'booking_active_1',
    operation: 'update',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      shootDate: '2026-11-05',
      totalPrice: 50, // Disallowed in affectedKeys().hasOnly()
      updatedAt: 'SERVER_TIMESTAMP',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 10,
    name: 'Immutable Timestamp Tampering (Forged Client updatedAt)',
    collection: 'bookings',
    docId: 'booking_active_1',
    operation: 'update',
    auth: { uid: 'user_1', email_verified: true },
    payload: {
      status: 'cancelled',
      updatedAt: '2020-01-01T00:00:00Z',
    },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 11,
    name: 'Unconstrained List Query Scraping Across Bookings',
    collection: 'bookings',
    docId: '*',
    operation: 'list',
    auth: { uid: 'user_1', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
  {
    id: 12,
    name: 'Path Variable ID Poisoning with Illegal Characters',
    collection: 'bookings',
    docId: 'malicious$id..//123',
    operation: 'create',
    auth: { uid: 'user_1', email_verified: true },
    expectedResult: 'PERMISSION_DENIED',
  },
];
